/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Workspace ID is not found on the request
 */
export type DeleteV2ResourcesEvaluatorsIdResponseBodyData = {
  message: string;
};

/**
 * Workspace ID is not found on the request
 */
export class DeleteV2ResourcesEvaluatorsIdResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: DeleteV2ResourcesEvaluatorsIdResponseBodyData;

  constructor(err: DeleteV2ResourcesEvaluatorsIdResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "DeleteV2ResourcesEvaluatorsIdResponseBody";
  }
}

/** @internal */
export const DeleteV2ResourcesEvaluatorsIdResponseBody$inboundSchema: z.ZodType<
  DeleteV2ResourcesEvaluatorsIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
})
  .transform((v) => {
    return new DeleteV2ResourcesEvaluatorsIdResponseBody(v);
  });

/** @internal */
export type DeleteV2ResourcesEvaluatorsIdResponseBody$Outbound = {
  message: string;
};

/** @internal */
export const DeleteV2ResourcesEvaluatorsIdResponseBody$outboundSchema:
  z.ZodType<
    DeleteV2ResourcesEvaluatorsIdResponseBody$Outbound,
    z.ZodTypeDef,
    DeleteV2ResourcesEvaluatorsIdResponseBody
  > = z.instanceof(DeleteV2ResourcesEvaluatorsIdResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteV2ResourcesEvaluatorsIdResponseBody$ {
  /** @deprecated use `DeleteV2ResourcesEvaluatorsIdResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    DeleteV2ResourcesEvaluatorsIdResponseBody$inboundSchema;
  /** @deprecated use `DeleteV2ResourcesEvaluatorsIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    DeleteV2ResourcesEvaluatorsIdResponseBody$outboundSchema;
  /** @deprecated use `DeleteV2ResourcesEvaluatorsIdResponseBody$Outbound` instead. */
  export type Outbound = DeleteV2ResourcesEvaluatorsIdResponseBody$Outbound;
}
