/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evaluatorsGetV2ResourcesEvaluatorsTemplates } from "../funcs/evaluatorsGetV2ResourcesEvaluatorsTemplates.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Evaluators extends ClientSDK {
  /**
   * Templates
   *
   * @remarks
   * List evaluators templates
   */
  async getV2ResourcesEvaluatorsTemplates(
    options?: RequestOptions,
  ): Promise<operations.GetV2ResourcesEvaluatorsTemplatesResponseBody> {
    return unwrapAsync(evaluatorsGetV2ResourcesEvaluatorsTemplates(
      this,
      options,
    ));
  }
}
