name: '[Stable] Generate'

on:
  push:
    branches:
      - main
    paths:
      - .speakeasy/gen.yaml

jobs:
  publish:
    uses: ./.github/workflows/sdk_generation.yml
    name: Runner
    secrets: inherit
    with:
      target: orq-test2-node
      npm_publish_tag_name: latest