name: '[Stable] Generate'

on:
  push:
    branches:
      - main
    paths:
      - .speakeasy/gen.yaml

jobs:
  publish:
    uses: ./.github/workflows/sdk_generation.yml
    name: Runner
    secrets: inherit
    with:
      is_production_release: true