name: '[Pre-release] Generate'

on:
  push:
    branches:
      - main
    paths:
      - packages/orq-rc/.speakeasy/gen.yaml

jobs:
  publish:
    uses: ./.github/workflows/sdk_generation.yml
    name: Runner
    secrets: inherit
    with:
      speakeasy_gen_config_path: packages/orq-rc/.speakeasy/gen.yaml